### ISSUE TITLE
Host Your Application

### ISSUE THREAD

**Issue by olacodesmentors** [harmydiano/wallet_system#1]

**Comment by olacodes** [comment]
Hi @harmydiano,

This is Sodiq (Decagon Software Engineer), It is obvious that the API documentation is hosted using Postman.
We also stated in the requirements that you host the application on any hosting platform of your choice such as Heroku, Digital Ocean, AWS etc and add the link to your readme.

Please feel free to close this issue when this requirement is effected.

**Comment by harmydiano** [comment]
Hi Sodiq, the solution was hosted on a private server. The link is in the
postman environmental variables, I will update the readme with the link.

**Comment by harmydiano** [comment]
@olacodes, it has been added
