### ISSUE TITLE
API not Accessible

### ISSUE THREAD

**Issue by olacodes** [harmydiano/wallet_system#2]
Hi @harmydiano,

I have tried to test your API with the BASE_URL environment variable you provided but still inaccessible. Added to this issue is the error sample image.

![error](https://user-images.githubusercontent.com/49355114/109398493-9f72d100-793d-11eb-90f8-73e2ba17fe9b.png)

**Comment by harmydiano** [comment]
Oh, Apologies please.. http://199.192.22.107:8000/api/v1

**Comment by harmydiano** [comment]
@olacodes , it should work now. Sorry for the inconvenience.
