### ISSUE TITLE
server error 

### ISSUE THREAD

**Issue by nnamdei** [harmydiano/wallet_system#3]
well done with your project. tried running your project locally and the register and login routes are returning server errors

**Comment by harmydiano** [comment]
Thanks @nnamdei , did you run it with the docker setup? I would be glad if you share the error.

**Comment by nnamdei** [comment]
> Thanks @nnamdei , did you run it with the docker setup? I would be glad if you share the error.

the mongo client is refusing connection.

web_1  |     (self._error_message(selector), timeout, self.description))
web_1  | pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 60466c32cc78bbf8b594911b, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused',)>]>

**Comment by harmydiano** [comment]
@nnamdei , it's been fixed. You can pull the code

**Comment by nnamdei** [comment]
Alright. How did you perform the tests as pytest is not picking any test cases. @harmydiano

**Comment by harmydiano** [comment]
The time for completion of the project had elapsed, so I had to share what I have. Though I had troubles running pytest at that time, it was a conflict between python 2.7 and 3. I just had to submit the project and reported the case to Chisom.
